# Generated by Django 3.1.7 on 2021-11-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='joined_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
