# Generated by Django 3.2.9 on 2021-11-12 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211108_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutual', models.BooleanField(default=False)),
                ('since', models.DateField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='backend.account')),
                ('following_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_id', to='backend.account')),
            ],
        ),
    ]
