# Generated by Django 3.2.9 on 2021-12-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_post_postcomment_postimage_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
