# Generated by Django 3.2.9 on 2021-12-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_account_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='mutual',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
